version: "2"
linters:
  default: none
  enable:
    - wsl_v5
  settings:
    wsl_v5:
      # https://github.com/bombsimon/wsl/tree/main?tab=readme-ov-file#configuration
      allow-first-in-block: true
      allow-whole-block: true
      branch-max-lines: 2
      case-max-lines: 2
      disable:
        # allow-cuddle-declarations: true (v4)
        - decl
        # allow-assign-and-call: true (v4)
        - assign-expr
