version: '3'

tasks:
  install:
    cmds:
      - echo "Installing dependencies"
      - cmd: sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
        platforms: [linux]
      - cmd: go install github.com/go-swagger/go-swagger/cmd/swagger@latest
      - cmd: go install github.com/wailsapp/wails/v2/cmd/wails@v2.5.1

  generate: go generate ./...

  clean:
    cmds:
      # kill the zombie goroutines
      - cmd: pgrep -f wallet.test | xargs -r kill -9 &>/dev/null
        platforms: [linux, darwin]
      - cmd: rm -f internal/handler/wallet/wallet_*.yaml &>/dev/null
        platforms: [linux, darwin]

  test: 
    cmds:
      - task: clean
      - cmd: go test -v -timeout 60s ./...

  fmt:
    cmds:
      - cmd: go mod tidy
      - cmd: gofumpt -l -w .
      - cmd: gci write .
      - cmd: golangci-lint run
      - task: fmt-wails
      - task: fmt-web

  fmt-wails:
    dir: wails-frontend
    cmds:
      - cmd: npm run fmt

  fmt-web:
    dir: web-frontend
    cmds:
      - cmd: npm run fmt

  build:
    cmds:
      - task: build-linux
      - task: build-macos
      - task: build-windows

  build-linux:
    platforms: [linux]
    cmds:
      - cmd: mkdir -p build/wallet-plugin
      - cmd: go build -o build/wallet-plugin/wallet-plugin -tags desktop,production -ldflags "-w -s" main.go

  build-macos:
    platforms: [darwin]
    cmds:
      - cmd: mkdir -p build/wallet-plugin
      - cmd: wails build -s
    env:
      CGO_LDFLAGS: -framework UniformTypeIdentifiers

  build-windows:
    platforms: [windows]
    cmds:
      - cmd: mkdir -p build/wallet-plugin
      - cmd: go build -tags desktop,production -ldflags "-w -s -H windowsgui" -o build/wallet-plugin/wallet-plugin.exe main.go

  build-webapp:
    dir: web-frontend
    cmds:
      - cmd: npm run build:standalone

  build-wails:
    dir: wails-frontend
    cmds:
      - cmd: npm run build

  wails-dev:
    cmds:
      - cmd: wails dev
    env:
      STANDALONE: 1

  install-plugin:
    cmds:
      - task: build
      - cmd: mkdir -p /usr/local/share/massastation/plugins/wallet-plugin
        platforms: [linux, darwin]
      - cmd: cp build/wallet-plugin/wallet-plugin /usr/local/share/massastation/plugins/wallet-plugin
        platforms: [linux, darwin]
      - cmd: cp wallet.svg /usr/local/share/massastation/plugins/wallet-plugin
        platforms: [linux, darwin]
      - cmd: cp manifest.json /usr/local/share/massastation/plugins/wallet-plugin
        platforms: [linux, darwin]

  run:
    cmds:
      - cmd: open -n ./build/bin/wallet-plugin.app/
        platforms: [darwin]
      - cmd: ./build/wallet-plugin/wallet-plugin
        platforms: [linux]
      - cmd: ./build/wallet-plugin/wallet-plugin.exe
        platforms: [windows]
    env:
      STANDALONE: 1

  build-run:
    cmds:
      - task: build-webapp
      - task: build-wails
      - task: build
      - task: run

  all:
    cmds:
      - task: install
      - task: generate
      - task: build
