// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortAction():Promise<void>;

export function ApplyPassword(arg1:string):Promise<void>;

export function Hide():Promise<void>;

export function Show():Promise<void>;
