// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPassword(arg1) {
  return window['go']['walletapp']['WalletApp']['ApplyPassword'](arg1);
}

export function Hide() {
  return window['go']['walletapp']['WalletApp']['Hide']();
}

export function PromptRequest(arg1, arg2, arg3) {
  return window['go']['walletapp']['WalletApp']['PromptRequest'](arg1, arg2, arg3);
}

export function Show() {
  return window['go']['walletapp']['WalletApp']['Show']();
}
