// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {walletapp} from '../models';

export function AbortAction():Promise<void>;

export function Hide():Promise<void>;

export function ImportPrivateKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectAccountFile():Promise<walletapp.selectFileResult>;

export function SendPromptInput(arg1:string):Promise<void>;

export function Show():Promise<void>;
