// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {walletapp} from '../models';

export function AbortAction():Promise<void>;

export function ApplyPassword(arg1:string):Promise<void>;

export function Hide():Promise<void>;

export function PromptRequest(arg1:walletapp.PromptRequest,arg2:string,arg3:any):Promise<void>;

export function Show():Promise<void>;
