// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortAction() {
  return window['go']['walletapp']['WalletApp']['AbortAction']();
}

export function ApplyPassword(arg1) {
  return window['go']['walletapp']['WalletApp']['ApplyPassword'](arg1);
}

export function Hide() {
  return window['go']['walletapp']['WalletApp']['Hide']();
}

export function ImportPrivateKey(arg1, arg2, arg3) {
  return window['go']['walletapp']['WalletApp']['ImportPrivateKey'](arg1, arg2, arg3);
}

export function ImportWalletFile(arg1) {
  return window['go']['walletapp']['WalletApp']['ImportWalletFile'](arg1);
}

export function SelectAccountFile() {
  return window['go']['walletapp']['WalletApp']['SelectAccountFile']();
}

export function Show() {
  return window['go']['walletapp']['WalletApp']['Show']();
}
