// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccountConfig Wallet Account Config.
//
// swagger:model AccountConfig
type AccountConfig struct {

	// sign rules
	// Required: true
	SignRules []*SignRule `json:"signRules"`
}

// Validate validates this account config
func (m *AccountConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSignRules(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountConfig) validateSignRules(formats strfmt.Registry) error {

	if err := validate.Required("signRules", "body", m.SignRules); err != nil {
		return err
	}

	for i := 0; i < len(m.SignRules); i++ {
		if swag.IsZero(m.SignRules[i]) { // not required
			continue
		}

		if m.SignRules[i] != nil {
			if err := m.SignRules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("signRules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("signRules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this account config based on the context it is used
func (m *AccountConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSignRules(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountConfig) contextValidateSignRules(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SignRules); i++ {

		if m.SignRules[i] != nil {

			if swag.IsZero(m.SignRules[i]) { // not required
				return nil
			}

			if err := m.SignRules[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("signRules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("signRules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountConfig) UnmarshalBinary(b []byte) error {
	var res AccountConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
