// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EditAccountRequest edit account request
//
// swagger:model EditAccountRequest
type EditAccountRequest struct {

	// new nickname
	NewNickname Nickname `json:"newNickname,omitempty"`
}

// Validate validates this edit account request
func (m *EditAccountRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewNickname(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EditAccountRequest) validateNewNickname(formats strfmt.Registry) error {
	if swag.IsZero(m.NewNickname) { // not required
		return nil
	}

	if err := m.NewNickname.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("newNickname")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("newNickname")
		}
		return err
	}

	return nil
}

// ContextValidate validate this edit account request based on the context it is used
func (m *EditAccountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNewNickname(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EditAccountRequest) contextValidateNewNickname(ctx context.Context, formats strfmt.Registry) error {

	if err := m.NewNickname.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("newNickname")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("newNickname")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EditAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditAccountRequest) UnmarshalBinary(b []byte) error {
	var res EditAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
