// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Nickname Account's short name.
//
// swagger:model Nickname
type Nickname string

// Validate validates this nickname
func (m Nickname) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this nickname based on context it is used
func (m Nickname) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
