// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Signature Signature of a sent operation.
//
// swagger:model Signature
type Signature struct {

	// Public part of the key pair used to sign the operation.
	// Required: true
	PublicKey string `json:"publicKey"`

	// Hash of the operation attributes encrypted with the private part of the key pair.
	// Required: true
	// Format: byte
	Signature strfmt.Base64 `json:"signature"`
}

// Validate validates this signature
func (m *Signature) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Signature) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.RequiredString("publicKey", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

func (m *Signature) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", strfmt.Base64(m.Signature)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this signature based on context it is used
func (m *Signature) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Signature) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Signature) UnmarshalBinary(b []byte) error {
	var res Signature
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
