// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SignRule Account Sign rule.
//
// swagger:model SignRule
type SignRule struct {

	// contract
	Contract *string `json:"contract,omitempty"`

	// enabled
	Enabled *bool `json:"enabled,omitempty"`

	// rule type
	// Required: true
	// Enum: ["password_prompt","auto_sign"]
	RuleType *string `json:"ruleType"`
}

// Validate validates this sign rule
func (m *SignRule) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRuleType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var signRuleTypeRuleTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["password_prompt","auto_sign"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		signRuleTypeRuleTypePropEnum = append(signRuleTypeRuleTypePropEnum, v)
	}
}

const (

	// SignRuleRuleTypePasswordPrompt captures enum value "password_prompt"
	SignRuleRuleTypePasswordPrompt string = "password_prompt"

	// SignRuleRuleTypeAutoSign captures enum value "auto_sign"
	SignRuleRuleTypeAutoSign string = "auto_sign"
)

// prop value enum
func (m *SignRule) validateRuleTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, signRuleTypeRuleTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SignRule) validateRuleType(formats strfmt.Registry) error {

	if err := validate.Required("ruleType", "body", m.RuleType); err != nil {
		return err
	}

	// value enum
	if err := m.validateRuleTypeEnum("ruleType", "body", *m.RuleType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sign rule based on context it is used
func (m *SignRule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignRule) UnmarshalBinary(b []byte) error {
	var res SignRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
