name: Install

inputs:
  # the input value is the 'runs-on'
  os:
    required: true
    default: 'ubuntu-latest'
  repo-token:
    description: The token to use to authenticate with the GitHub API
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Xcode
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ inputs.repo-token }}

    - name: Install Dependencies
      run: task install
      shell: bash

    - name: Add go/bin into PATH
      shell: bash
      run: export PATH=$PATH:$(go env GOPATH)/bin

    - name: build frontends
      shell: bash
      run: |
        go generate ./wails-frontend
        go generate ./web-frontend
