name: Install

inputs:
  # the input value is the 'runs-on'
  os:
    required: true
    default: 'ubuntu-latest'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Xcode
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@${{inputs.wails-version}}
      shell: bash
    - name: Install Linux Wails deps
      if:  runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
      shell: bash
    - name: Install macOS Wails deps
      if: runner.os == 'macOS'
      run: brew install mitchellh/gon/gon
      shell: bash

    - name: Add go/bin into PATH
      shell: bash
      run: export PATH=$PATH:$(go env GOPATH)/bin

    - name: build frontends
      shell: bash
      run: |
        go generate ./wails-frontend
        go generate ./web-frontend
