name: Install

inputs:
  # the input value is the 'runs-on'
  os:
    required: true
    default: 'ubuntu-latest'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Xcode
      if: ${{ inputs.os == 'macos-latest' }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    # install dependencies for build for target linux and windows
    - name: installing Linux dependencies
      if: startsWith(inputs.os, 'ubuntu-')
      shell: bash
      run: |
        sudo apt update
        sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev

    - name: installing Go Swagger and wails
      shell: bash
      run: |
        go install github.com/go-swagger/go-swagger/cmd/swagger@latest
    - name: running Go generate
      shell: bash
      run: |
        go generate ./...
        
