name: Sign a given file

inputs:
  file:
    required: true
    description: The file to sign

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Download Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Prepapre environment for signature
      run: |
        curl -L -o jsign.jar https://github.com/ebourg/jsign/releases/download/5.0/jsign-5.0.jar
        echo "${{ vars.GCP_PEM_KEY }}" > codesign-chain.pem

    - name: Sign massastation with EV cert on Google Cloud
      run: |
        java -jar jsign.jar --storetype GOOGLECLOUD --storepass "$(gcloud auth print-access-token)" --keystore "${{ secrets.GCP_KEYSTORE_ID }}" --alias "${{ secrets.GCP_KEY_ALIAS }}" --certfile "codesign-chain.pem" --tsmode RFC3161 --tsaurl http://timestamp.globalsign.com/tsa/r6advanced1 ${{ inputs.file }}
