// Code generated by go-swagger; DO NOT EDIT.

// Package restapi massa-core-plugin
//
//  Massa core Thyra plugin.
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 0.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - image/png
//    - text/css
//    - text/html
//    - text/javascript
//    - application/json
//    - text/webp
//
// swagger:meta
package restapi
