// Code generated by go-swagger; DO NOT EDIT.

// Package restapi massa-wallet
//
//	MassaStation plugin - Wallet
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/png
//	  - text/css
//	  - text/html
//	  - text/javascript
//	  - application/json
//	  - text/webp
//
// swagger:meta
package restapi
