// Code generated by go-swagger; DO NOT EDIT.

// Package restapi massa-wallet
//
//	Thyra plugin - Massa wallet
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/png
//	  - text/css
//	  - text/html
//	  - text/javascript
//	  - application/json
//	  - text/webp
//
// swagger:meta
package restapi
