// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AccountListHandlerFunc turns a function with the right signature into a account list handler
type AccountListHandlerFunc func(AccountListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AccountListHandlerFunc) Handle(params AccountListParams) middleware.Responder {
	return fn(params)
}

// AccountListHandler interface for that can handle valid account list params
type AccountListHandler interface {
	Handle(AccountListParams) middleware.Responder
}

// NewAccountList creates a new http.Handler for the account list operation
func NewAccountList(ctx *middleware.Context, handler AccountListHandler) *AccountList {
	return &AccountList{Context: ctx, Handler: handler}
}

/*
	AccountList swagger:route GET /api/accounts accountList

Get all the accounts.
*/
type AccountList struct {
	Context *middleware.Context
	Handler AccountListHandler
}

func (o *AccountList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAccountListParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
