// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/massalabs/station-massa-wallet/api/server/models"
)

// AddAssetHandlerFunc turns a function with the right signature into a add asset handler
type AddAssetHandlerFunc func(AddAssetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddAssetHandlerFunc) Handle(params AddAssetParams) middleware.Responder {
	return fn(params)
}

// AddAssetHandler interface for that can handle valid add asset params
type AddAssetHandler interface {
	Handle(AddAssetParams) middleware.Responder
}

// NewAddAsset creates a new http.Handler for the add asset operation
func NewAddAsset(ctx *middleware.Context, handler AddAssetHandler) *AddAsset {
	return &AddAsset{Context: ctx, Handler: handler}
}

/*
	AddAsset swagger:route POST /api/assets addAsset

Add MRC-20 token information and persist it for future use.
*/
type AddAsset struct {
	Context *middleware.Context
	Handler AddAssetHandler
}

func (o *AddAsset) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddAssetParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// AddAssetCreatedBody add asset created body
//
// swagger:model AddAssetCreatedBody
type AddAssetCreatedBody struct {

	// assets
	Assets []models.AssetInfo `json:"assets"`
}

// Validate validates this add asset created body
func (o *AddAssetCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAssets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddAssetCreatedBody) validateAssets(formats strfmt.Registry) error {
	if swag.IsZero(o.Assets) { // not required
		return nil
	}

	for i := 0; i < len(o.Assets); i++ {

		if err := o.Assets[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("addAssetCreated" + "." + "assets" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("addAssetCreated" + "." + "assets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// ContextValidate validate this add asset created body based on the context it is used
func (o *AddAssetCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAssets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddAssetCreatedBody) contextValidateAssets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Assets); i++ {

		if err := o.Assets[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("addAssetCreated" + "." + "assets" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("addAssetCreated" + "." + "assets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *AddAssetCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddAssetCreatedBody) UnmarshalBinary(b []byte) error {
	var res AddAssetCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// AddAssetPartialContentBody add asset partial content body
//
// swagger:model AddAssetPartialContentBody
type AddAssetPartialContentBody struct {

	// assets
	Assets []models.AssetInfo `json:"assets"`
}

// Validate validates this add asset partial content body
func (o *AddAssetPartialContentBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAssets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddAssetPartialContentBody) validateAssets(formats strfmt.Registry) error {
	if swag.IsZero(o.Assets) { // not required
		return nil
	}

	for i := 0; i < len(o.Assets); i++ {

		if err := o.Assets[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("addAssetPartialContent" + "." + "assets" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("addAssetPartialContent" + "." + "assets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// ContextValidate validate this add asset partial content body based on the context it is used
func (o *AddAssetPartialContentBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAssets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AddAssetPartialContentBody) contextValidateAssets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Assets); i++ {

		if err := o.Assets[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("addAssetPartialContent" + "." + "assets" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("addAssetPartialContent" + "." + "assets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *AddAssetPartialContentBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddAssetPartialContentBody) UnmarshalBinary(b []byte) error {
	var res AddAssetPartialContentBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
