// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/station-massa-wallet/api/server/models"
)

// CreateAccountOKCode is the HTTP code returned for type CreateAccountOK
const CreateAccountOKCode int = 200

/*
CreateAccountOK New account created.

swagger:response createAccountOK
*/
type CreateAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.Account `json:"body,omitempty"`
}

// NewCreateAccountOK creates CreateAccountOK with default headers values
func NewCreateAccountOK() *CreateAccountOK {

	return &CreateAccountOK{}
}

// WithPayload adds the payload to the create account o k response
func (o *CreateAccountOK) WithPayload(payload *models.Account) *CreateAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account o k response
func (o *CreateAccountOK) SetPayload(payload *models.Account) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountBadRequestCode is the HTTP code returned for type CreateAccountBadRequest
const CreateAccountBadRequestCode int = 400

/*
CreateAccountBadRequest Bad request.

swagger:response createAccountBadRequest
*/
type CreateAccountBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAccountBadRequest creates CreateAccountBadRequest with default headers values
func NewCreateAccountBadRequest() *CreateAccountBadRequest {

	return &CreateAccountBadRequest{}
}

// WithPayload adds the payload to the create account bad request response
func (o *CreateAccountBadRequest) WithPayload(payload *models.Error) *CreateAccountBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account bad request response
func (o *CreateAccountBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountUnauthorizedCode is the HTTP code returned for type CreateAccountUnauthorized
const CreateAccountUnauthorizedCode int = 401

/*
CreateAccountUnauthorized Unauthorized - The request requires user authentication.

swagger:response createAccountUnauthorized
*/
type CreateAccountUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAccountUnauthorized creates CreateAccountUnauthorized with default headers values
func NewCreateAccountUnauthorized() *CreateAccountUnauthorized {

	return &CreateAccountUnauthorized{}
}

// WithPayload adds the payload to the create account unauthorized response
func (o *CreateAccountUnauthorized) WithPayload(payload *models.Error) *CreateAccountUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account unauthorized response
func (o *CreateAccountUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountUnprocessableEntityCode is the HTTP code returned for type CreateAccountUnprocessableEntity
const CreateAccountUnprocessableEntityCode int = 422

/*
CreateAccountUnprocessableEntity Unprocessable Entity - syntax is correct, but the server was unable to process the contained instructions.

swagger:response createAccountUnprocessableEntity
*/
type CreateAccountUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAccountUnprocessableEntity creates CreateAccountUnprocessableEntity with default headers values
func NewCreateAccountUnprocessableEntity() *CreateAccountUnprocessableEntity {

	return &CreateAccountUnprocessableEntity{}
}

// WithPayload adds the payload to the create account unprocessable entity response
func (o *CreateAccountUnprocessableEntity) WithPayload(payload *models.Error) *CreateAccountUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account unprocessable entity response
func (o *CreateAccountUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountInternalServerErrorCode is the HTTP code returned for type CreateAccountInternalServerError
const CreateAccountInternalServerErrorCode int = 500

/*
CreateAccountInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response createAccountInternalServerError
*/
type CreateAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAccountInternalServerError creates CreateAccountInternalServerError with default headers values
func NewCreateAccountInternalServerError() *CreateAccountInternalServerError {

	return &CreateAccountInternalServerError{}
}

// WithPayload adds the payload to the create account internal server error response
func (o *CreateAccountInternalServerError) WithPayload(payload *models.Error) *CreateAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account internal server error response
func (o *CreateAccountInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
