// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DefaultPageMovedPermanentlyCode is the HTTP code returned for type DefaultPageMovedPermanently
const DefaultPageMovedPermanentlyCode int = 301

/*
DefaultPageMovedPermanently Move to the default endpoint

swagger:response defaultPageMovedPermanently
*/
type DefaultPageMovedPermanently struct {
}

// NewDefaultPageMovedPermanently creates DefaultPageMovedPermanently with default headers values
func NewDefaultPageMovedPermanently() *DefaultPageMovedPermanently {

	return &DefaultPageMovedPermanently{}
}

// WriteResponse to the client
func (o *DefaultPageMovedPermanently) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(301)
}
