// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSignRuleHandlerFunc turns a function with the right signature into a delete sign rule handler
type DeleteSignRuleHandlerFunc func(DeleteSignRuleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSignRuleHandlerFunc) Handle(params DeleteSignRuleParams) middleware.Responder {
	return fn(params)
}

// DeleteSignRuleHandler interface for that can handle valid delete sign rule params
type DeleteSignRuleHandler interface {
	Handle(DeleteSignRuleParams) middleware.Responder
}

// NewDeleteSignRule creates a new http.Handler for the delete sign rule operation
func NewDeleteSignRule(ctx *middleware.Context, handler DeleteSignRuleHandler) *DeleteSignRule {
	return &DeleteSignRule{Context: ctx, Handler: handler}
}

/*
	DeleteSignRule swagger:route DELETE /api/accounts/{nickname}/signrules/{ruleId} deleteSignRule

Delete a sign rule for the account associated with the provided nickname by its ID.
*/
type DeleteSignRule struct {
	Context *middleware.Context
	Handler DeleteSignRuleHandler
}

func (o *DeleteSignRule) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteSignRuleParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
