// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAccountHandlerFunc turns a function with the right signature into a delete account handler
type DeleteAccountHandlerFunc func(DeleteAccountParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAccountHandlerFunc) Handle(params DeleteAccountParams) middleware.Responder {
	return fn(params)
}

// DeleteAccountHandler interface for that can handle valid delete account params
type DeleteAccountHandler interface {
	Handle(DeleteAccountParams) middleware.Responder
}

// NewDeleteAccount creates a new http.Handler for the delete account operation
func NewDeleteAccount(ctx *middleware.Context, handler DeleteAccountHandler) *DeleteAccount {
	return &DeleteAccount{Context: ctx, Handler: handler}
}

/*
	DeleteAccount swagger:route DELETE /api/accounts/{nickname} deleteAccount

Delete the account associated with the provided nickname in the path, the user will be prompt to confirm the deletion.
*/
type DeleteAccount struct {
	Context *middleware.Context
	Handler DeleteAccountHandler
}

func (o *DeleteAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAccountParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
