// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// EditAccountHandlerFunc turns a function with the right signature into a edit account handler
type EditAccountHandlerFunc func(EditAccountParams) middleware.Responder

// Handle executing the request and returning a response
func (fn EditAccountHandlerFunc) Handle(params EditAccountParams) middleware.Responder {
	return fn(params)
}

// EditAccountHandler interface for that can handle valid edit account params
type EditAccountHandler interface {
	Handle(EditAccountParams) middleware.Responder
}

// NewEditAccount creates a new http.Handler for the edit account operation
func NewEditAccount(ctx *middleware.Context, handler EditAccountHandler) *EditAccount {
	return &EditAccount{Context: ctx, Handler: handler}
}

/*
	EditAccount swagger:route PUT /api/accounts/{nickname} editAccount

Edit the account associated with the provided nickname in the path.
*/
type EditAccount struct {
	Context *middleware.Context
	Handler EditAccountHandler
}

func (o *EditAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewEditAccountParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
