// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetAllAssetsParams creates a new GetAllAssetsParams object
//
// There are no default values defined in the spec.
func NewGetAllAssetsParams() GetAllAssetsParams {

	return GetAllAssetsParams{}
}

// GetAllAssetsParams contains all the bound params for the get all assets operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAllAssets
type GetAllAssetsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The nickname of the wallet to retrieve assets for.
	  Required: true
	  In: query
	*/
	WalletNickname string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAllAssetsParams() beforehand.
func (o *GetAllAssetsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qWalletNickname, qhkWalletNickname, _ := qs.GetOK("walletNickname")
	if err := o.bindWalletNickname(qWalletNickname, qhkWalletNickname, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindWalletNickname binds and validates parameter WalletNickname from query.
func (o *GetAllAssetsParams) bindWalletNickname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("walletNickname", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("walletNickname", "query", raw); err != nil {
		return err
	}
	o.WalletNickname = raw

	return nil
}
