// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/station-massa-wallet/api/server/models"
)

// GetAllAssetsOKCode is the HTTP code returned for type GetAllAssetsOK
const GetAllAssetsOKCode int = 200

/*
GetAllAssetsOK Asset information retrieved successfully.

swagger:response getAllAssetsOK
*/
type GetAllAssetsOK struct {

	/*
	  In: Body
	*/
	Payload *GetAllAssetsOKBody `json:"body,omitempty"`
}

// NewGetAllAssetsOK creates GetAllAssetsOK with default headers values
func NewGetAllAssetsOK() *GetAllAssetsOK {

	return &GetAllAssetsOK{}
}

// WithPayload adds the payload to the get all assets o k response
func (o *GetAllAssetsOK) WithPayload(payload *GetAllAssetsOKBody) *GetAllAssetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all assets o k response
func (o *GetAllAssetsOK) SetPayload(payload *GetAllAssetsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllAssetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllAssetsBadRequestCode is the HTTP code returned for type GetAllAssetsBadRequest
const GetAllAssetsBadRequestCode int = 400

/*
GetAllAssetsBadRequest Bad request.

swagger:response getAllAssetsBadRequest
*/
type GetAllAssetsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllAssetsBadRequest creates GetAllAssetsBadRequest with default headers values
func NewGetAllAssetsBadRequest() *GetAllAssetsBadRequest {

	return &GetAllAssetsBadRequest{}
}

// WithPayload adds the payload to the get all assets bad request response
func (o *GetAllAssetsBadRequest) WithPayload(payload *models.Error) *GetAllAssetsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all assets bad request response
func (o *GetAllAssetsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllAssetsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllAssetsNotFoundCode is the HTTP code returned for type GetAllAssetsNotFound
const GetAllAssetsNotFoundCode int = 404

/*
GetAllAssetsNotFound Not found - At least one of the provided addresses is not valid.

swagger:response getAllAssetsNotFound
*/
type GetAllAssetsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllAssetsNotFound creates GetAllAssetsNotFound with default headers values
func NewGetAllAssetsNotFound() *GetAllAssetsNotFound {

	return &GetAllAssetsNotFound{}
}

// WithPayload adds the payload to the get all assets not found response
func (o *GetAllAssetsNotFound) WithPayload(payload *models.Error) *GetAllAssetsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all assets not found response
func (o *GetAllAssetsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllAssetsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllAssetsInternalServerErrorCode is the HTTP code returned for type GetAllAssetsInternalServerError
const GetAllAssetsInternalServerErrorCode int = 500

/*
GetAllAssetsInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response getAllAssetsInternalServerError
*/
type GetAllAssetsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllAssetsInternalServerError creates GetAllAssetsInternalServerError with default headers values
func NewGetAllAssetsInternalServerError() *GetAllAssetsInternalServerError {

	return &GetAllAssetsInternalServerError{}
}

// WithPayload adds the payload to the get all assets internal server error response
func (o *GetAllAssetsInternalServerError) WithPayload(payload *models.Error) *GetAllAssetsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all assets internal server error response
func (o *GetAllAssetsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllAssetsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
