// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ModifyAccountNicknameHandlerFunc turns a function with the right signature into a modify account nickname handler
type ModifyAccountNicknameHandlerFunc func(ModifyAccountNicknameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ModifyAccountNicknameHandlerFunc) Handle(params ModifyAccountNicknameParams) middleware.Responder {
	return fn(params)
}

// ModifyAccountNicknameHandler interface for that can handle valid modify account nickname params
type ModifyAccountNicknameHandler interface {
	Handle(ModifyAccountNicknameParams) middleware.Responder
}

// NewModifyAccountNickname creates a new http.Handler for the modify account nickname operation
func NewModifyAccountNickname(ctx *middleware.Context, handler ModifyAccountNicknameHandler) *ModifyAccountNickname {
	return &ModifyAccountNickname{Context: ctx, Handler: handler}
}

/*
	ModifyAccountNickname swagger:route PUT /api/accounts/{nickname} modifyAccountNickname

Modify the account nickname
*/
type ModifyAccountNickname struct {
	Context *middleware.Context
	Handler ModifyAccountNicknameHandler
}

func (o *ModifyAccountNickname) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewModifyAccountNicknameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
