// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RestWalletSignOperationHandlerFunc turns a function with the right signature into a rest wallet sign operation handler
type RestWalletSignOperationHandlerFunc func(RestWalletSignOperationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RestWalletSignOperationHandlerFunc) Handle(params RestWalletSignOperationParams) middleware.Responder {
	return fn(params)
}

// RestWalletSignOperationHandler interface for that can handle valid rest wallet sign operation params
type RestWalletSignOperationHandler interface {
	Handle(RestWalletSignOperationParams) middleware.Responder
}

// NewRestWalletSignOperation creates a new http.Handler for the rest wallet sign operation operation
func NewRestWalletSignOperation(ctx *middleware.Context, handler RestWalletSignOperationHandler) *RestWalletSignOperation {
	return &RestWalletSignOperation{Context: ctx, Handler: handler}
}

/*
	RestWalletSignOperation swagger:route POST /rest/wallet/{nickname}/signOperation restWalletSignOperation

RestWalletSignOperation rest wallet sign operation API
*/
type RestWalletSignOperation struct {
	Context *middleware.Context
	Handler RestWalletSignOperationHandler
}

func (o *RestWalletSignOperation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRestWalletSignOperationParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
