// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/thyra-plugin-wallet/api/server/models"
)

// RestCreateAccountOKCode is the HTTP code returned for type RestCreateAccountOK
const RestCreateAccountOKCode int = 200

/*
RestCreateAccountOK New account created.

swagger:response restCreateAccountOK
*/
type RestCreateAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.Account `json:"body,omitempty"`
}

// NewRestCreateAccountOK creates RestCreateAccountOK with default headers values
func NewRestCreateAccountOK() *RestCreateAccountOK {

	return &RestCreateAccountOK{}
}

// WithPayload adds the payload to the rest create account o k response
func (o *RestCreateAccountOK) WithPayload(payload *models.Account) *RestCreateAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest create account o k response
func (o *RestCreateAccountOK) SetPayload(payload *models.Account) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestCreateAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RestCreateAccountBadRequestCode is the HTTP code returned for type RestCreateAccountBadRequest
const RestCreateAccountBadRequestCode int = 400

/*
RestCreateAccountBadRequest Bad request.

swagger:response restCreateAccountBadRequest
*/
type RestCreateAccountBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRestCreateAccountBadRequest creates RestCreateAccountBadRequest with default headers values
func NewRestCreateAccountBadRequest() *RestCreateAccountBadRequest {

	return &RestCreateAccountBadRequest{}
}

// WithPayload adds the payload to the rest create account bad request response
func (o *RestCreateAccountBadRequest) WithPayload(payload *models.Error) *RestCreateAccountBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest create account bad request response
func (o *RestCreateAccountBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestCreateAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RestCreateAccountUnauthorizedCode is the HTTP code returned for type RestCreateAccountUnauthorized
const RestCreateAccountUnauthorizedCode int = 401

/*
RestCreateAccountUnauthorized Unauthorized - The request requires user authentication. Only if no correlationId is provided.

swagger:response restCreateAccountUnauthorized
*/
type RestCreateAccountUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRestCreateAccountUnauthorized creates RestCreateAccountUnauthorized with default headers values
func NewRestCreateAccountUnauthorized() *RestCreateAccountUnauthorized {

	return &RestCreateAccountUnauthorized{}
}

// WithPayload adds the payload to the rest create account unauthorized response
func (o *RestCreateAccountUnauthorized) WithPayload(payload *models.Error) *RestCreateAccountUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest create account unauthorized response
func (o *RestCreateAccountUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestCreateAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RestCreateAccountUnprocessableEntityCode is the HTTP code returned for type RestCreateAccountUnprocessableEntity
const RestCreateAccountUnprocessableEntityCode int = 422

/*
RestCreateAccountUnprocessableEntity Unprocessable Entity - syntax is correct, but the server was unable to process the contained instructions.

swagger:response restCreateAccountUnprocessableEntity
*/
type RestCreateAccountUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRestCreateAccountUnprocessableEntity creates RestCreateAccountUnprocessableEntity with default headers values
func NewRestCreateAccountUnprocessableEntity() *RestCreateAccountUnprocessableEntity {

	return &RestCreateAccountUnprocessableEntity{}
}

// WithPayload adds the payload to the rest create account unprocessable entity response
func (o *RestCreateAccountUnprocessableEntity) WithPayload(payload *models.Error) *RestCreateAccountUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest create account unprocessable entity response
func (o *RestCreateAccountUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestCreateAccountUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RestCreateAccountInternalServerErrorCode is the HTTP code returned for type RestCreateAccountInternalServerError
const RestCreateAccountInternalServerErrorCode int = 500

/*
RestCreateAccountInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response restCreateAccountInternalServerError
*/
type RestCreateAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRestCreateAccountInternalServerError creates RestCreateAccountInternalServerError with default headers values
func NewRestCreateAccountInternalServerError() *RestCreateAccountInternalServerError {

	return &RestCreateAccountInternalServerError{}
}

// WithPayload adds the payload to the rest create account internal server error response
func (o *RestCreateAccountInternalServerError) WithPayload(payload *models.Error) *RestCreateAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest create account internal server error response
func (o *RestCreateAccountInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestCreateAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
