// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RestWalletDeleteHandlerFunc turns a function with the right signature into a rest wallet delete handler
type RestWalletDeleteHandlerFunc func(RestWalletDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RestWalletDeleteHandlerFunc) Handle(params RestWalletDeleteParams) middleware.Responder {
	return fn(params)
}

// RestWalletDeleteHandler interface for that can handle valid rest wallet delete params
type RestWalletDeleteHandler interface {
	Handle(RestWalletDeleteParams) middleware.Responder
}

// NewRestWalletDelete creates a new http.Handler for the rest wallet delete operation
func NewRestWalletDelete(ctx *middleware.Context, handler RestWalletDeleteHandler) *RestWalletDelete {
	return &RestWalletDelete{Context: ctx, Handler: handler}
}

/*
	RestWalletDelete swagger:route DELETE /rest/wallet/{nickname} restWalletDelete

RestWalletDelete rest wallet delete API
*/
type RestWalletDelete struct {
	Context *middleware.Context
	Handler RestWalletDeleteHandler
}

func (o *RestWalletDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRestWalletDeleteParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
