// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/thyra-plugin-wallet/api/server/models"
)

// RestAccountDeleteNoContentCode is the HTTP code returned for type RestAccountDeleteNoContent
const RestAccountDeleteNoContentCode int = 204

/*
RestAccountDeleteNoContent Account deletion request has been taken into account, the user will be prompt to confirm the deletion.

swagger:response restAccountDeleteNoContent
*/
type RestAccountDeleteNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.Account `json:"body,omitempty"`
}

// NewRestAccountDeleteNoContent creates RestAccountDeleteNoContent with default headers values
func NewRestAccountDeleteNoContent() *RestAccountDeleteNoContent {

	return &RestAccountDeleteNoContent{}
}

// WithPayload adds the payload to the rest account delete no content response
func (o *RestAccountDeleteNoContent) WithPayload(payload *models.Account) *RestAccountDeleteNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest account delete no content response
func (o *RestAccountDeleteNoContent) SetPayload(payload *models.Account) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestAccountDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RestAccountDeleteBadRequestCode is the HTTP code returned for type RestAccountDeleteBadRequest
const RestAccountDeleteBadRequestCode int = 400

/*
RestAccountDeleteBadRequest Bad request.

swagger:response restAccountDeleteBadRequest
*/
type RestAccountDeleteBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRestAccountDeleteBadRequest creates RestAccountDeleteBadRequest with default headers values
func NewRestAccountDeleteBadRequest() *RestAccountDeleteBadRequest {

	return &RestAccountDeleteBadRequest{}
}

// WithPayload adds the payload to the rest account delete bad request response
func (o *RestAccountDeleteBadRequest) WithPayload(payload *models.Error) *RestAccountDeleteBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest account delete bad request response
func (o *RestAccountDeleteBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestAccountDeleteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RestAccountDeleteNotFoundCode is the HTTP code returned for type RestAccountDeleteNotFound
const RestAccountDeleteNotFoundCode int = 404

/*
RestAccountDeleteNotFound Not found.

swagger:response restAccountDeleteNotFound
*/
type RestAccountDeleteNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRestAccountDeleteNotFound creates RestAccountDeleteNotFound with default headers values
func NewRestAccountDeleteNotFound() *RestAccountDeleteNotFound {

	return &RestAccountDeleteNotFound{}
}

// WithPayload adds the payload to the rest account delete not found response
func (o *RestAccountDeleteNotFound) WithPayload(payload *models.Error) *RestAccountDeleteNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest account delete not found response
func (o *RestAccountDeleteNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestAccountDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RestAccountDeleteInternalServerErrorCode is the HTTP code returned for type RestAccountDeleteInternalServerError
const RestAccountDeleteInternalServerErrorCode int = 500

/*
RestAccountDeleteInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response restAccountDeleteInternalServerError
*/
type RestAccountDeleteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRestAccountDeleteInternalServerError creates RestAccountDeleteInternalServerError with default headers values
func NewRestAccountDeleteInternalServerError() *RestAccountDeleteInternalServerError {

	return &RestAccountDeleteInternalServerError{}
}

// WithPayload adds the payload to the rest account delete internal server error response
func (o *RestAccountDeleteInternalServerError) WithPayload(payload *models.Error) *RestAccountDeleteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rest account delete internal server error response
func (o *RestAccountDeleteInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RestAccountDeleteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
