// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// RetrieveAssetInfoListURL generates an URL for the retrieve asset info list operation
type RetrieveAssetInfoListURL struct {
	AssetAddresses []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *RetrieveAssetInfoListURL) WithBasePath(bp string) *RetrieveAssetInfoListURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *RetrieveAssetInfoListURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *RetrieveAssetInfoListURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/api/assets"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var assetAddressesIR []string
	for _, assetAddressesI := range o.AssetAddresses {
		assetAddressesIS := assetAddressesI
		if assetAddressesIS != "" {
			assetAddressesIR = append(assetAddressesIR, assetAddressesIS)
		}
	}

	assetAddresses := swag.JoinByFormat(assetAddressesIR, "")

	if len(assetAddresses) > 0 {
		qsv := assetAddresses[0]
		if qsv != "" {
			qs.Set("assetAddresses", qsv)
		}
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *RetrieveAssetInfoListURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *RetrieveAssetInfoListURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *RetrieveAssetInfoListURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on RetrieveAssetInfoListURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on RetrieveAssetInfoListURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *RetrieveAssetInfoListURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
