// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/station-massa-wallet/api/server/models"
)

// RetrieveAssetInfoListOKCode is the HTTP code returned for type RetrieveAssetInfoListOK
const RetrieveAssetInfoListOKCode int = 200

/*
RetrieveAssetInfoListOK Asset information retrieved successfully.

swagger:response retrieveAssetInfoListOK
*/
type RetrieveAssetInfoListOK struct {

	/*
	  In: Body
	*/
	Payload *RetrieveAssetInfoListOKBody `json:"body,omitempty"`
}

// NewRetrieveAssetInfoListOK creates RetrieveAssetInfoListOK with default headers values
func NewRetrieveAssetInfoListOK() *RetrieveAssetInfoListOK {

	return &RetrieveAssetInfoListOK{}
}

// WithPayload adds the payload to the retrieve asset info list o k response
func (o *RetrieveAssetInfoListOK) WithPayload(payload *RetrieveAssetInfoListOKBody) *RetrieveAssetInfoListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve asset info list o k response
func (o *RetrieveAssetInfoListOK) SetPayload(payload *RetrieveAssetInfoListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveAssetInfoListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveAssetInfoListBadRequestCode is the HTTP code returned for type RetrieveAssetInfoListBadRequest
const RetrieveAssetInfoListBadRequestCode int = 400

/*
RetrieveAssetInfoListBadRequest Bad request.

swagger:response retrieveAssetInfoListBadRequest
*/
type RetrieveAssetInfoListBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRetrieveAssetInfoListBadRequest creates RetrieveAssetInfoListBadRequest with default headers values
func NewRetrieveAssetInfoListBadRequest() *RetrieveAssetInfoListBadRequest {

	return &RetrieveAssetInfoListBadRequest{}
}

// WithPayload adds the payload to the retrieve asset info list bad request response
func (o *RetrieveAssetInfoListBadRequest) WithPayload(payload *models.Error) *RetrieveAssetInfoListBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve asset info list bad request response
func (o *RetrieveAssetInfoListBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveAssetInfoListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveAssetInfoListNotFoundCode is the HTTP code returned for type RetrieveAssetInfoListNotFound
const RetrieveAssetInfoListNotFoundCode int = 404

/*
RetrieveAssetInfoListNotFound Not found - At least one of the provided addresses is not valid.

swagger:response retrieveAssetInfoListNotFound
*/
type RetrieveAssetInfoListNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRetrieveAssetInfoListNotFound creates RetrieveAssetInfoListNotFound with default headers values
func NewRetrieveAssetInfoListNotFound() *RetrieveAssetInfoListNotFound {

	return &RetrieveAssetInfoListNotFound{}
}

// WithPayload adds the payload to the retrieve asset info list not found response
func (o *RetrieveAssetInfoListNotFound) WithPayload(payload *models.Error) *RetrieveAssetInfoListNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve asset info list not found response
func (o *RetrieveAssetInfoListNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveAssetInfoListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveAssetInfoListInternalServerErrorCode is the HTTP code returned for type RetrieveAssetInfoListInternalServerError
const RetrieveAssetInfoListInternalServerErrorCode int = 500

/*
RetrieveAssetInfoListInternalServerError Internal Server Error - The server has encountered a situation it does not know how to handle.

swagger:response retrieveAssetInfoListInternalServerError
*/
type RetrieveAssetInfoListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRetrieveAssetInfoListInternalServerError creates RetrieveAssetInfoListInternalServerError with default headers values
func NewRetrieveAssetInfoListInternalServerError() *RetrieveAssetInfoListInternalServerError {

	return &RetrieveAssetInfoListInternalServerError{}
}

// WithPayload adds the payload to the retrieve asset info list internal server error response
func (o *RetrieveAssetInfoListInternalServerError) WithPayload(payload *models.Error) *RetrieveAssetInfoListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve asset info list internal server error response
func (o *RetrieveAssetInfoListInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveAssetInfoListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
