// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/massalabs/station-massa-wallet/api/server/models"
)

// RetrieveAssetInfoListHandlerFunc turns a function with the right signature into a retrieve asset info list handler
type RetrieveAssetInfoListHandlerFunc func(RetrieveAssetInfoListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RetrieveAssetInfoListHandlerFunc) Handle(params RetrieveAssetInfoListParams) middleware.Responder {
	return fn(params)
}

// RetrieveAssetInfoListHandler interface for that can handle valid retrieve asset info list params
type RetrieveAssetInfoListHandler interface {
	Handle(RetrieveAssetInfoListParams) middleware.Responder
}

// NewRetrieveAssetInfoList creates a new http.Handler for the retrieve asset info list operation
func NewRetrieveAssetInfoList(ctx *middleware.Context, handler RetrieveAssetInfoListHandler) *RetrieveAssetInfoList {
	return &RetrieveAssetInfoList{Context: ctx, Handler: handler}
}

/*
	RetrieveAssetInfoList swagger:route POST /api/assets retrieveAssetInfoList

Retrieve MRC-20 token information for a list of asset addresses and persist it for future use.
*/
type RetrieveAssetInfoList struct {
	Context *middleware.Context
	Handler RetrieveAssetInfoListHandler
}

func (o *RetrieveAssetInfoList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRetrieveAssetInfoListParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// RetrieveAssetInfoListOKBody retrieve asset info list o k body
//
// swagger:model RetrieveAssetInfoListOKBody
type RetrieveAssetInfoListOKBody struct {

	// assets
	Assets []models.AssetInfo `json:"assets"`
}

// Validate validates this retrieve asset info list o k body
func (o *RetrieveAssetInfoListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAssets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RetrieveAssetInfoListOKBody) validateAssets(formats strfmt.Registry) error {
	if swag.IsZero(o.Assets) { // not required
		return nil
	}

	for i := 0; i < len(o.Assets); i++ {

		if err := o.Assets[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("retrieveAssetInfoListOK" + "." + "assets" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("retrieveAssetInfoListOK" + "." + "assets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// ContextValidate validate this retrieve asset info list o k body based on the context it is used
func (o *RetrieveAssetInfoListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAssets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RetrieveAssetInfoListOKBody) contextValidateAssets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Assets); i++ {

		if err := o.Assets[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("retrieveAssetInfoListOK" + "." + "assets" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("retrieveAssetInfoListOK" + "." + "assets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *RetrieveAssetInfoListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RetrieveAssetInfoListOKBody) UnmarshalBinary(b []byte) error {
	var res RetrieveAssetInfoListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// RetrieveAssetInfoListPartialContentBody retrieve asset info list partial content body
//
// swagger:model RetrieveAssetInfoListPartialContentBody
type RetrieveAssetInfoListPartialContentBody struct {

	// assets
	Assets []models.AssetInfo `json:"assets"`
}

// Validate validates this retrieve asset info list partial content body
func (o *RetrieveAssetInfoListPartialContentBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAssets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RetrieveAssetInfoListPartialContentBody) validateAssets(formats strfmt.Registry) error {
	if swag.IsZero(o.Assets) { // not required
		return nil
	}

	for i := 0; i < len(o.Assets); i++ {

		if err := o.Assets[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("retrieveAssetInfoListPartialContent" + "." + "assets" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("retrieveAssetInfoListPartialContent" + "." + "assets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// ContextValidate validate this retrieve asset info list partial content body based on the context it is used
func (o *RetrieveAssetInfoListPartialContentBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAssets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RetrieveAssetInfoListPartialContentBody) contextValidateAssets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Assets); i++ {

		if err := o.Assets[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("retrieveAssetInfoListPartialContent" + "." + "assets" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("retrieveAssetInfoListPartialContent" + "." + "assets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *RetrieveAssetInfoListPartialContentBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RetrieveAssetInfoListPartialContentBody) UnmarshalBinary(b []byte) error {
	var res RetrieveAssetInfoListPartialContentBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
