// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateSignRuleHandlerFunc turns a function with the right signature into a update sign rule handler
type UpdateSignRuleHandlerFunc func(UpdateSignRuleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSignRuleHandlerFunc) Handle(params UpdateSignRuleParams) middleware.Responder {
	return fn(params)
}

// UpdateSignRuleHandler interface for that can handle valid update sign rule params
type UpdateSignRuleHandler interface {
	Handle(UpdateSignRuleParams) middleware.Responder
}

// NewUpdateSignRule creates a new http.Handler for the update sign rule operation
func NewUpdateSignRule(ctx *middleware.Context, handler UpdateSignRuleHandler) *UpdateSignRule {
	return &UpdateSignRule{Context: ctx, Handler: handler}
}

/*
	UpdateSignRule swagger:route PUT /api/accounts/{nickname}/signrules/{ruleId} updateSignRule

Update an existing sign rule for the account associated with the provided nickname by its ID.
*/
type UpdateSignRule struct {
	Context *middleware.Context
	Handler UpdateSignRuleHandler
}

func (o *UpdateSignRule) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateSignRuleParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
