// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/station-massa-wallet/api/server/models"
)

// WebAppOKCode is the HTTP code returned for type WebAppOK
const WebAppOKCode int = 200

/*
WebAppOK Page found

swagger:response webAppOK
*/
type WebAppOK struct {
}

// NewWebAppOK creates WebAppOK with default headers values
func NewWebAppOK() *WebAppOK {

	return &WebAppOK{}
}

// WriteResponse to the client
func (o *WebAppOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// WebAppNotFoundCode is the HTTP code returned for type WebAppNotFound
const WebAppNotFoundCode int = 404

/*
WebAppNotFound Resource not found.

swagger:response webAppNotFound
*/
type WebAppNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewWebAppNotFound creates WebAppNotFound with default headers values
func NewWebAppNotFound() *WebAppNotFound {

	return &WebAppNotFound{}
}

// WithPayload adds the payload to the web app not found response
func (o *WebAppNotFound) WithPayload(payload *models.Error) *WebAppNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the web app not found response
func (o *WebAppNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WebAppNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
