name: e2e Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: build
        run: go build -tags desktop,production,webkit2_41 -ldflags "-w -s" -o build/test_wallet main.go
      - name: Run app
        run: WALLET_PASSWORD=bonjour STANDALONE=1 xvfb-run ./build/test_wallet &
      - name: Move account file
        run: |
          mkdir -p ~/.config/massa-station-wallet
          cp tests/wallet_bonjour.yaml ~/.config/massa-station-wallet/wallet_bonjour.yaml
      - name: test wallet loaded
        run: |
          sleep 5
          NBWALLET=$(curl http://localhost:8080/api/accounts/ | jq '. | length')
          if [[ "$NBWALLET" != "1" ]]; then
            echo "wallet not loaded"
            exit 1
          fi
      - name: Delete Wallet
        run: |
          curl -X DELETE http://localhost:8080/api/accounts/bonjour
      - name: test wallet delete
        run: |
          sleep 1
          NBWALLET=$(curl http://localhost:8080/api/accounts/ | jq '. | length')
          if [[ "$NBWALLET" != "0" ]]; then
            echo "wallet not deleted"
            exit 1
          fi
  robot-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: build
        run: go build -tags desktop,production -ldflags "-w -s" -o build/test_wallet main.go
      - name: Set up wallet
        run: |
          mkdir -p $HOME/.config/massa-station-wallet/
          echo "$WALLET_TEST_WALLET" > $HOME/.config/massa-station-wallet/wallet_fullpower.yaml
      - name: Run app
        run: STANDALONE=1 xvfb-run ./build/test_wallet > logs.txt &
        env:
          WALLET_PASSWORD: ${{ secrets.WALLET_TEST_PASSWORD }}
      - name: Wait for server to be up
        uses: juliangruber/sleep-action@v1
        with:
          time: 5s
      - name: Run RobotFramework tests
        working-directory: api/test
        run: |
          mkdir results
          robot --outputdir results robot_tests
      - name: Print logs
        if: always()
        run: cat logs.txt
