name: Update Manifest

on:
  release:
    types:
      - published

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Manifest
        run: |
          # Retrieve the latest tag name
          TAG_NAME=$(git describe --tags --abbrev=0)
          
          # Update the version field in the manifest.json file
          sed -i "s/\"version\": \".*\",/\"version\": \"$TAG_NAME\",/" manifest.json

      - name: Commit changes
        run: |
          git add ../../manifest.json
          git commit -m "Update version in manifest.json" --no-verify
          git push
